DROP TABLE IF EXISTS PRODUCT_CATEGORY CASCADE;

DROP TABLE IF EXISTS PAYMENT CASCADE;

DROP TABLE IF EXISTS ORDER_ITEM CASCADE;

DROP TABLE IF EXISTS ORDERS CASCADE;

DROP TABLE IF EXISTS INVENTORY CASCADE;

DROP TABLE IF EXISTS CUSTOMER CASCADE;

DROP TABLE IF EXISTS PRODUCT CASCADE;

DROP TABLE IF EXISTS CATEGORY CASCADE;

DROP TYPE IF EXISTS ORDER_STATUS CASCADE;

DROP TYPE IF EXISTS PAYMENT_STATUS CASCADE;

DROP TYPE IF EXISTS PAYMENT_METHOD CASCADE;

-- Skapa ENUM-typer för orderstatus och betalningsstatus
CREATE TYPE ORDER_STATUS AS ENUM('NEW', 'PAID', 'CANCELLED');

CREATE TYPE PAYMENT_STATUS AS ENUM('PENDING', 'APPROVED', 'DECLINED');

CREATE TYPE PAYMENT_METHOD AS ENUM('CARD', 'INVOICE');

-- Skapa tabellen för Kategorier
CREATE TABLE CATEGORY (
	CATEGORY_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL
);

-- Skapa tabellen för Produkter
CREATE TABLE PRODUCT (
	PRODUCT_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	SKU VARCHAR(100) UNIQUE NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION TEXT,
	PRICE DECIMAL(10, 2) NOT NULL,
	ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Skapa tabellen för Kunder
CREATE TABLE CUSTOMER (
	CUSTOMER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	EMAIL VARCHAR(255) UNIQUE NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Skapa tabellen för Lager
CREATE TABLE INVENTORY (
	INVENTORY_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	PRODUCT_ID INT NOT NULL REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE,
	QUANTITY INT NOT NULL CHECK (QUANTITY >= 0)
);

-- Skapa tabellen för Ordrar
CREATE TABLE ORDERS (
	ORDER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CUSTOMER_ID INT NOT NULL REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE CASCADE,
	STATUS ORDER_STATUS NOT NULL,
	TOTAL DECIMAL(10, 2) NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Skapa tabellen för Orderobjekt (OrderItems)
CREATE TABLE ORDER_ITEM (
	ORDER_ID INT NOT NULL REFERENCES ORDERS (ORDER_ID) ON DELETE CASCADE,
	PRODUCT_ID INT NOT NULL REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE,
	QUANTITY INT NOT NULL CHECK (QUANTITY > 0),
	UNIT_PRICE DECIMAL(10, 2) NOT NULL,
	LINE_TOTAL DECIMAL(10, 2) GENERATED ALWAYS AS (QUANTITY * UNIT_PRICE) STORED,
	PRIMARY KEY (ORDER_ID, PRODUCT_ID)
);

-- Skapa tabellen för Betalningar
CREATE TABLE PAYMENT (
	PAYMENT_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ORDER_ID INT NOT NULL REFERENCES ORDERS (ORDER_ID) ON DELETE CASCADE,
	METHOD PAYMENT_METHOD NOT NULL,
	STATUS PAYMENT_STATUS NOT NULL,
	TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE ORDERS ADD COLUMN PAYMENT_ID INT NOT NULL REFERENCES PAYMENT (PAYMENT_ID) ON DELETE CASCADE;
-- Skapa en kopplingstabell för Produkter och Kategorier (många-till-många)
CREATE TABLE PRODUCT_CATEGORY (
	PRODUCT_ID INT NOT NULL REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE,
	CATEGORY_ID INT NOT NULL REFERENCES CATEGORY (CATEGORY_ID) ON DELETE CASCADE,
	PRIMARY KEY (PRODUCT_ID, CATEGORY_ID)
);